import type { Metadata } from "next";
import "./globals.css";
import { monaSansFont } from "./fonts";
import { Outfit } from "next/font/google";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

const fontOutfit = Outfit({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trove Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monaSansFont.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
